language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Examples/Node
install:
    - pip install -U platformio

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/#!/lib/show/7/U8glib
    # http://platformio.org/#!/lib/show/38/LowPower
    # http://platformio.org/#!/lib/show/125/SPIFlash
    # http://platformio.org/#!/lib/show/131/TimerOne
    # http://platformio.org/#!/lib/show/136/LiquidCrystal
    # http://platformio.org/#!/lib/show/176/NewPing
    # http://platformio.org/#!/lib/show/531/WirelessHEX69
    # http://platformio.org/#!/lib/show/532/BMP180
    # http://platformio.org/#!/lib/show/536/Si7021

    - platformio lib install 7 38 125 131 136 176 531 532 536

    #- wget https://bitbucket.org/fmalpartida/st7036-display-driver/downloads/LCD_%20ST7036_v1.2.0.zip -O /tmp/st7036_source.zip
    #- unzip /tmp/st7036_source.zip -d /tmp/

script:
    #- platformio ci --board=moteino --lib=. --lib="/tmp/LCD_C0220BIZ"
    - platformio ci --board=moteino --lib=.
